/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/desk.glb 
Author: woodbang (https://sketchfab.com/woodbang)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/woodbang-touchey-parametric-coffee-table-oak-6f7a02bb69ca4cc7b8e81cf3df7011ae
Title: Woodbang Touchey parametric coffee table / Oak
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/desk.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Woodbang_Touchey_coffee_table_Material__90_0.geometry} material={materials.Material__90} rotation={[-Math.PI, 0, 0]} scale={0.001} />
      </group>
    </group>
  )
}

useGLTF.preload('/desk.glb')
